### ISSUE TITLE
Cannot build a top level PossibleWorld 

### ISSUE THREAD

**Issue by Fabalab** [gchq/MagmaCore#194]
**Describe the bug**
Every possible_world inherits from state and, therefore, must be part of a possible_world. To break the recursion, (ie. for a top-level possible_world) a self reference is needed. However, this is not possible using the builder classes supplied in hqdm-canonical. Should there be an extra, `partOfOwnPossibleWorld()` method on the `PossibleWorldBuilder` class that allows you to make this self-referential relationship?

**To Reproduce**
Run the following code:
```
final IRI topLevelWorldIri = new IRI(HQDM.HQDM, "Top_Level_World");
final PossibleWorldBuilder topLevelWorldBuilder = new PossibleWorldBuilder(topLevelWorldIri);
final PossibleWorld topLevelWorld = topLevelWorldBuilder.build();
```
It will return the following error:
```
Exception in thread "main" uk.gov.gchq.magmacore.hqdm.exception.HqdmException: Property Not Set: part_of_possible_world
	at uk.gov.gchq.magmacore.hqdm.rdfbuilders.PossibleWorldBuilder.build(PossibleWorldBuilder.java:268)
	at main.Program.main(Program.java:20)
```

**Comment by twalmsley** [comment]
Hi @Fabalab @ClimbingAl , I was going to answer this yesterday but was too busy. The examples from @ClimbingAl are all good, but here are my thoughts as well.

I didn't want to update the builder for possible world to refer to itself because this would end up being the default and people wouldn't then think about the problem, so I'm glad to see that you have looked into it! Another alternative I considered earlier was to have a well-known IRI defined in the library for a possible world that represents our world, the world outside any computer system, to act as the root of all possible worlds within any computer system. The 'universal possible world' could then be supplied when using the builder. It's something to think about but in the meantime any of the alternatives above will do.
